### ISSUE TITLE
A problem with the path to manually download the dataset

### ISSUE THREAD

**Issue by HUAjijiji** [Kubasinska/MI-EEG-1D-CNN#21]
Hello, I am a postgraduate student who just started studying BCI;
I tried running this code on my computer (Windows10, using anaconda to install python environment)；
I now have the Python environment installed, but I encountered the following error while performing this step (Generate the dataset):
![image](https://user-images.githubusercontent.com/58539055/163184257-cbecf771-bc78-4ace-a69d-cc41f30d2494.png)
FileNotFoundError: [WinError 3],The system could not find the specified path: './MI-EEG-1D-CNN-master/files/paper\\FC1FC2'

I have downloaded and unpacked the dataset myself,I put this data set under the D:\CODE\MI-EEG-1D-CNN-master path.
I actually saw you talking about it in readme:Change the dataset path to the path of the dataset you downloaded, and you are ready!
I have tried several times and failed, so I come here for help. What should I do?
Sincerely hope to get your reply

**Comment by Kubasinska** [comment]
Thanks for your interest.  If you need anything else, do not hesitate to write me.  I will close the issue. 😄
