### ISSUE TITLE
Questions about the operation of script train_d.py and train_e.py

### ISSUE THREAD

**Issue by HUAjijiji** [Kubasinska/MI-EEG-1D-CNN#23]
I'm sorry to bother you. I set up the required environment on a ubuntu18 computer a few days ago and also ran the tran_a,b,c scripts without any problems.

I use jupyter lab to view and run the code.train_a,b,c They all run smoothly as shown below:
![1](https://user-images.githubusercontent.com/58539055/163939426-1c43c7f8-7a7e-40f1-b406-7e2d59ae3ff0.png)They can train to complete.
  
When I run the scripts train_d and train_e, the script stops running when it prints out 
  " before oversampling=[     ] " (as if it had already finished). 
![2](https://user-images.githubusercontent.com/58539055/163940115-108415cd-ece6-4561-b1c7-989db6b3249f.png)
Confusingly, there is no error reported either.

I am unable to solve this problem on my own for the time being and would appreciate your suggestions in your free time.

Additional note: I used pycharm to run these scripts in a windows 10 environment and they all worked fine.

**Comment by Kubasinska** [comment]
I think the problem is your GPU memory. In any case, [zewail-liu](https://github.com/zewail-liu) recently pointed out a bug in the code that could invalidate this work, please read issue #22 carefully.
